### ISSUE TITLE
Decryption failed despite being able to encrypt message

### ISSUE THREAD

**Issue by kekkoudesu** [konstantintutsch/Lock#27] opened 2024-11-23 09:47 UTC
### Describe the bug …

1. Write a message, `test` and click Encrypt, then select a specific key.
2. Click Decrypt - it fails:
![image](https://github.com/user-attachments/assets/aa438a09-b405-448b-9915-2eeaf09345bf)

It only seems to fail with that key. I've gotten the same process to work with another key I have (no passphrase). It seems likely that the private key has not been unlocked and I'm not prompted to unlock it.  I went and committed some code, which was automatically signed with the same private key.  I tried to Decrypt again, and this time it worked. I was never asked for a passphrase to sign it...

Here's my `gpg-agent.conf`:

```
$ cat ~/.gnupg/gpg-agent.conf
pinentry-program /usr/bin/pinentry-gnome3
max-cache-ttl 14400
default-cache-ttl 14400
```

If this is indeed the issue, I think the error message should be improved. I'm also not quite sure what's happening here or how I managed to "fix" it...

### Which version of Lock are you using?

1.1.2

### Source

Flathub

### Relevant log output

```shell
I don't get any output aside from the application name/version number.
```

**Comment by konstantintutsch** [comment] 2024-11-23 10:28
Are you sure there is no log output? All GPGME library calls should produce an error message when they fail.

You also provided the version of GPGME, not Lock. Locks version can be retrieved from the about dialog. Could you please fix that?

**Comment by kekkoudesu** [comment] 2024-11-23 10:34
How do I get log output? I've tried 

```
flatpak run --command=sh com.konstantintutsch.Lock
```

Then:

```
/app/bin/com.konstantintutsch.Lock
```

The only thing I saw was:

```
** Message: 21:30:56.468: GnuPG Made Easy 1.23.2
```

I'm seeing a few extra messages this time:

```
MESA-INTEL: warning: ../src/intel/vulkan/anv_formats.c:763: FINISHME: support YUV colorspace with DRM format modifiers
MESA-INTEL: warning: ../src/intel/vulkan/anv_formats.c:794: FINISHME: support more multi-planar formats with DRM modifiers

(com.konstantintutsch.Lock:3): Gsk-WARNING **: 21:31:43.534: Clipping is broken, everything is clipped, but we didn't early-exit.
```

I'm not able to reproduce the issue at the moment as the key appears to be unlocked after using it to sign a commit. I'll see if I can reboot and hit the same issue, then update this tracker.

**Comment by konstantintutsch** [comment] 2024-11-23 10:59
> How do I get log output? I've tried

Just execute `flatpak run com.konstantintutsch.Lock`.

You do not need to enter the shell and then manually run the Lock binary. That also works though, it is just more effort.

**Comment by kekkoudesu** [comment] 2024-11-24 02:24
Okay, I rebooted and was able to reproduce the issue. It is indeed failing to show me the prompt:

```
** (com.konstantintutsch.Lock:2): WARNING **: 13:24:14.919: Failed to decrypt GPGME data from memory: pinentry error
```

**Comment by konstantintutsch** [comment] 2024-11-24 07:27
This seems to be a duplicate of #30

**Closed as not planned by konstantintutsch** 2024-11-24 07:27 UTC
Labels: bug, duplicate
