### ISSUE TITLE
Pinentry fails in Flatpak

### ISSUE THREAD

**Issue by TellThatToLuke** [konstantintutsch/Lock#30] opened 2024-11-23 19:24 UTC
### Describe the bug …

Lock cannot make use of the system Pinentry.

The Pinentry program is available and GnuPG's configuration is matching https://github.com/konstantintutsch/Lock/issues/23#issuecomment-2470065961.

### Which version of Lock are you using?

1.1.3

### Source

Flathub

### Relevant log output

```shell
** (com.konstantintutsch.Lock:2): WARNING **: 19:21:51.300: Failed to sign GPGME data from memory: pinentry error
```

**Comment by konstantintutsch** [comment] 2024-11-23 21:50
Could you please check if this is a duplicate of https://github.com/konstantintutsch/Lock/issues/23#issuecomment-2470065961?

**Comment by TellThatToLuke** [comment] 2024-11-23 21:52
> Could you please check if this is a duplicate of [#23 (comment)](https://github.com/konstantintutsch/Lock/issues/23#issuecomment-2470065961)?

I followed them instructions, but the issue still persisted.

**Comment by konstantintutsch** [comment] 2024-11-23 21:54
Did you reboot before trying again?

**Comment by TellThatToLuke** [comment] 2024-11-23 21:57
Yes, I reviewed all the issues related to pinentry and followed the instructions in your comment before submitting my issue.

**Comment by konstantintutsch** [comment] 2024-11-23 21:59
Does this command produce output?

```
flatpak run --command=pinentry-gnome3 com.konstantintutsch.Lock
```

**Comment by TellThatToLuke** [comment] 2024-11-23 22:01
I received the following output:
```
OK Pleased to meet you, process 2
```

**Comment by konstantintutsch** [comment] 2024-11-23 22:04
Can you try another cryptography operation, e. g. encrypting, and then report back if you encountered the same error there?

**Comment by TellThatToLuke** [comment] 2024-11-23 22:10
Verifying and encrypting do not encounter an error; however, decrypting does encounter the same error.
```shell
** (com.konstantintutsch.Lock:2): WARNING **: 22:09:17.583: Failed to decrypt GPGME data from memory: pinentry error
```

**Comment by konstantintutsch** [comment] 2024-11-23 22:15
Do you encounter the same error when using GnuPG directly via the command line?

**Comment by TellThatToLuke** [comment] 2024-11-23 22:16
> Verifying and encrypting do not encounter an error; however, decrypting does encounter the same error.
> 
> ```shell
> ** (com.konstantintutsch.Lock:2): WARNING **: 22:09:17.583: Failed to decrypt GPGME data from memory: pinentry error
> ```

Adding to this, I also encounter the same error when generating a new keypair:
```shell
** (com.konstantintutsch.Lock:2): WARNING **: 22:14:04.198: Failed to generate new GPG key for signing: pinentry error
```



> Do you encounter the same error when using GnuPG directly via the command line?

I do not.

**Comment by TellThatToLuke** [comment] 2024-11-23 22:47
I have identified the cause of the error for the signing and decrypting cryptography operation. If you generate a keypair with a passphrase via the command line and don't save the passphrase in your password manager, you will encounter the error. However, I am still encountering the error when generating a new key pair.

**Comment by TellThatToLuke** [comment] 2024-11-23 22:57
It is intended that when you perform a signing operation, the default key is used? I do not have the same behaviour as the encrypting operation when prompted to select a key.

**Comment by TellThatToLuke** [comment] 2024-11-23 23:41
> However, I am still encountering the error when generating a new keypair.

I am unsure of a resolution. Despite removing all keys, I still encountered the error for this operation.

**Comment by konstantintutsch** [comment] 2024-11-24 07:23
> I have identified the cause of the error for the signing and decrypting cryptography operation. If you generate a keypair with a passphrase via the command line and don't save the passphrase in your password manager, you will encounter the error. However, I am still encountering the error when generating a new keypair.

That solution is just circumventing the actual problem. You removed the need for a Pinentry to open because your system keyring already unlocked the key automatically.

**Comment by konstantintutsch** [comment] 2024-11-24 07:26
> It is intended that when you perform a signing operation, the default key is used? I do not have the same behaviour as the encrypting operation when prompted to select a key.

Yes, the default key is used. I'll implement key selection for signing too. Never even though of that 😂

Completely overlooked this piece of [documentation](https://www.gnupg.org/documentation/manuals/gpgme/Selecting-Signers.html) …

**Comment by konstantintutsch** [comment] 2024-11-24 07:44
@TellThatToLuke @kekkoudesu Which Linux distribution are you running?

Please also provide the versions of GPG, pinentry-gnome3 and GPGME.

**Comment by konstantintutsch** [comment] 2024-11-24 10:30
Could reproduce the error. This seems to be an issue with Flatpak.

**Closed** 2024-11-24 11:35 UTC
Labels: bug

**Comment by TellThatToLuke** [comment] 2024-11-24 16:51
> @TellThatToLuke @kekkoudesu Which Linux distribution are you running?
> 
> Please also provide the versions of GPG, pinentry-gnome3 and GPGME.

Arch Linux 6.12.1
gnupg 2.4.6
pinentry 1.3.1
gpgme 1.24.0

> > However, I am still encountering the error when generating a new keypair.
> 
> I am unsure of a resolution. Despite removing all keys, I still encountered the error for this operation.

I am still encountering this issue with https://github.com/konstantintutsch/Lock/commit/38a3be6a97d0f475fbd63f30484bf311b39a2ead.

**Comment by konstantintutsch** [comment] 2024-11-24 16:53
Did you reboot after updating Lock?

**Comment by TellThatToLuke** [comment] 2024-11-24 17:06
I rebooted, imported the private keys I had removed without saving the passphrases, and it turns out the issue still persists with verifying, decrypting, as well as generating a new keypair.

**Comment by konstantintutsch** [comment] 2024-11-24 17:09
Would you be able to build Lock on your system outside of the Flatpak sandbox?

```
meson setup builddir
cd ./builddir
meson compile
sudo meson install
```

- Run Lock: `com.konstantintutsch.Lock`
- Remove Lock: `sudo ninja uninstall`

**Comment by TellThatToLuke** [comment] 2024-11-24 17:13
> I rebooted, imported the private keys I had removed without saving the passphrases, and it turns out the issue still persists with verifying, decrypting, as well as generating a new keypair.

Here's a demonstration:

https://github.com/user-attachments/assets/657020e7-4c51-4c3b-8ccb-ead41ab72b59

**Comment by TellThatToLuke** [comment] 2024-11-24 17:21
> Would you be able to build Lock on your system outside of the Flatpak sandbox?
> 
> ```
> meson setup builddir
> cd ./builddir
> meson compile
> sudo meson install
> ```
> 
>     * Run Lock: `com.konstantintutsch.Lock`
> 
>     * Remove Lock: `sudo ninja uninstall`

No issues are present.

**Comment by TellThatToLuke** [comment] 2024-11-24 17:46
I've identified that the issues are caused by having the `'gpg-agent'` socket enabled in the sandbox.

**Comment by konstantintutsch** [comment] 2024-11-24 18:00
I did not expect that Lock is still functional with a separate GnuPG Agent instance. I definitely did not work when I set up Flatpak builds.

Thank you for discovering that! This is also really great for sandboxing purposes and philosophy.

**Comment by konstantintutsch** [comment] 2024-11-24 18:07
All further progress will be managed in #32

My assumption about this issue being fixed was a bit too spontaneous. Well, I'll learn from this :D
